apiVersion: v2
name: ib-gateway
description: A Helm chart for deploying Interactive Brokers Gateway on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

# Ajout d'une icône (optionnel mais recommandé)
icon: https://www.interactivebrokers.com/images/web/logos/ib-logo-dark.svg

# Informations sur le maintainer
maintainers:
  - name: Qantor Capital
    email: contact@qantorcapital.com

# Mots-clés pour faciliter la recherche
keywords:
  - trading
  - interactive-brokers
  - gateway
  - finance

# Annotations additionnelles
annotations:
  category: Finance

# Type de licence
license: MIT