# Configuration du namespace
namespace:
  name: "trading"

# Configuration du secret
secret:
  name: "ib-gateway-secrets"

# Configuration de l'image
image:
  repository: voyz/ib-gateway-docker
  tag: latest
  pullPolicy: IfNotPresent

# Configuration IB Gateway
ibgateway:
  mode: "paper"
  port: "4001"
  apiPort: "4002"
  timezone: "Europe/Paris"

# Configuration VNC
vnc:
  enabled: true
  port: "5900"
  password: "myVNCpass"

# Configuration du service
service:
  type: ClusterIP

# Configuration des ressources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Configuration du stockage
persistence:
  enabled: true
  size: "1Gi"
  accessMode: ReadWriteOnce
  storageClass: "standard"

# Configuration de la sécurité
security:
  autoRestartOnDisconnect: true

# Configuration des logs
logging:
  level: "INFO"