# Configuration du namespace
namespace:
  name: "trading"

# Configuration du secret
secret:
  name: "ib-gateway-secrets"

# Configuration de l'image
image:
  repository: ghcr.io/uijin/ib-gateway-arm64
  tag: latest
  pullPolicy: IfNotPresent

# Configuration IB Gateway
ibgateway:
  mode: "paper"  # "paper" ou "live"
  port: "4001"
  apiPort: "4002"
  timezone: "Europe/Paris"

# Configuration VNC
vnc:
  enabled: true
  port: "5900"
  password: "myVNCpass"

# Configuration du service
service:
  type: LoadBalancer  # Changé pour permettre l'accès externe
  annotations: {}     # Pour cloud providers spécifiques

# Configuration des ressources
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Configuration du stockage
persistence:
  enabled: true
  size: "1Gi"
  accessMode: ReadWriteOnce
  storageClass: "local-path"

# Configuration de la sécurité
security:
  autoRestartOnDisconnect: true
  allowedIPs: []  # Nouvelle option pour la sécurité réseau
  # Example:
  # allowedIPs:
  #   - "192.168.1.0/24"
  #   - "10.0.0.0/8"

# Configuration des logs
logging:
  level: "INFO"
  persistence:
    enabled: true
    size: "500Mi"
    retention: "7d"

# Configuration supervisor (nouveau)
supervisor:
  enabled: true
  logLevel: "info"

# Configuration des sondes (nouveau)
probes:
  readiness:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
  liveness:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 20