# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ib-gateway-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: ib-gateway
data:
  TWS_PORT: "{{ .Values.ibgateway.port }}"
  API_PORT: "{{ .Values.ibgateway.apiPort }}"
  TRADING_MODE: "{{ .Values.ibgateway.mode }}"
  TZ: "{{ .Values.ibgateway.timezone }}"
  LOG_LEVEL: "{{ .Values.logging.level }}"
  {{- if .Values.security.autoRestartOnDisconnect }}
  IBC_AUTO_RESTART_ON_DISCONNECT: "yes"
  {{- end }}
  {{- if .Values.vnc.enabled }}
  VNC_SERVER_PASSWORD: "{{ .Values.vnc.password }}"
  {{- end }}
