# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ib-gateway
  namespace: {{ .Values.namespace.name }}
  labels:
    app: ib-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ib-gateway
  template:
    metadata:
      labels:
        app: ib-gateway
    spec:
      containers:
        - name: ib-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tws
              containerPort: {{ .Values.ibgateway.port }}
              protocol: TCP
            - name: api
              containerPort: {{ .Values.ibgateway.apiPort }}
              protocol: TCP
            {{- if .Values.vnc.enabled }}
            - name: vnc
              containerPort: {{ .Values.vnc.port }}
              protocol: TCP
            {{- end }}
          env:
            - name: TWS_USERID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username
            - name: TWS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password
            - name: IB_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: account
          envFrom:
            - configMapRef:
                name: ib-gateway-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /root/IBController/Logs
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ib-gateway-pvc
      {{- end }}